-- Beautia 정보글 시드 (검증된 내용 · 사진 전부 다름 · 저경쟁 키워드 제목)
-- Supabase SQL Editor에서 1회 실행 → 커뮤니티 '정보' 게시판에 13개 글 등록
insert into public.posts (nickname,cat,region,title,content,tags,imgs,created_at) values
('Beautia','정보','전체',E'일본 미용실 필수 일본어 — 다운펌·매직·뿌리염색 일본어로?',E'일본 미용실에서 자주 막히는 시술 용어를 일본어로 정리했어요.\n\n· 다운펌(자연스럽게) → ストレートパーマ (스토레토파마)\n· 매직/강한 직모교정 → 縮毛矯正 (슈쿠모쿄세이)\n· 뿌리염색 → リタッチカラー (리탓치카라)\n· 기장 유지 → 長さはあまり切らないで\n· 사진 보여주며 → こんな感じにしたいです\n\n부담되면 사진 + Beautia 통역으로 디테일까지 전달돼요.',ARRAY['일본미용실','일본어','다운펌','매직']::text[],ARRAY['https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '1 hours'),
('Beautia','정보','도쿄',E'도쿄에서 한국어 되는 미용실 찾는 법 (신주쿠·신오쿠보)',E'도쿄에서 한국어로 머리하고 싶다면?\n\n· 신오쿠보(新大久保) = 도쿄 코리아타운 → 한국어·한국식 펌/컷 가능한 곳 많아요\n· 신주쿠·시부야 일반 살롱도 사진+통역이면 OK\n· 한국식 다운펌·뿌리염색은 한인 미용실이 편해요\n\n어디든 일본어 0이어도 Beautia가 한국어로 예약·통역 대행. 지역별 정보 → beautia.io/info',ARRAY['도쿄미용실','한국어','신오쿠보','워홀']::text[],ARRAY['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '10 hours'),
('Beautia','정보','오사카',E'오사카에서 한국어 되는 네일샵 (츠루하시·신사이바시)',E'오사카 네일, 일본어 못해도 가능해요.\n\n· 츠루하시(鶴橋) = 오사카 코리아타운, 한국어 OK\n· 신사이바시·난바 = 트렌디한 네일샵 밀집\n· 사진 1장이면 디자인 거의 그대로 재현\n\n한국어 안 되는 곳도 Beautia 통역으로 커버. → beautia.io/info/osaka-nail',ARRAY['오사카네일','한국어','츠루하시']::text[],ARRAY['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '19 hours'),
('Beautia','정보','전체',E'일본 미용실·네일 예약 방법 (핫페퍼뷰티 + 한국어 대행)',E'일본 미용 예약은 보통 이렇게 해요.\n\n· ホットペッパービューティー(핫페퍼뷰티) = 일본 최대 예약 앱, 쿠폰 많음\n· 인기 살롱은 워크인 어려워 2~3일 전 예약 권장\n· 일본어 입력이 어렵다면 한국어로 신청 → Beautia가 일본어 예약·통역 대행(무료)\n\n사진·요청사항 미리 저장해두면 더 정확해요.',ARRAY['일본미용실','예약','핫페퍼뷰티']::text[],ARRAY['https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '28 hours'),
('Beautia','정보','전체',E'일본 네일 가격 정리 (젤·아트·연장 / 엔·원)',E'엔저라 지금 일본 네일이 합리적이에요. (팁 없음 = 표시가 그대로)\n\n· 젤네일 원컬러: ¥4,000~7,000 (약 3.7~6.5만원)\n· 젤 아트: ¥7,000~13,000\n· 연장(스컬프): ¥10,000~18,000\n· 오프(제거): ¥1,500~3,000\n\n※ 매장·디자인·시점에 따라 다름. 지역별 가격 → beautia.io/info',ARRAY['일본네일','가격','엔저']::text[],ARRAY['https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '37 hours'),
('Beautia','정보','전체',E'일본 미용실 가격 정리 (컷·펌·염색)',E'일본 미용실 평균 가격대예요.\n\n· 컷: ¥4,000~8,000\n· 펌: ¥10,000~20,000\n· 염색(전체): ¥8,000~16,000\n· 다운펌/매직: ¥12,000~25,000\n\n팁 문화가 없어 표시가가 곧 결제 금액. 지명 디자이너는 지명료가 붙기도 해요.',ARRAY['일본미용실','가격','펌','염색']::text[],ARRAY['https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '46 hours'),
('Beautia','정보','도쿄',E'일본 속눈썹 연장 가격 + 라쉬리프트 일본어',E'일본 속눈썹(아이래시)은 자연스럽고 합리적이에요.\n\n· 연장(80~100본): ¥4,000~7,000\n· 볼륨래시: ¥6,000~10,000\n· 속눈썹 펌(라쉬리프트) → ラッシュリフト / まつげパーマ\n· 속눈썹 전문샵 = まつエクサロン\n\n시술 후 몇 시간 세안 주의 → 일정 마지막에 받는 걸 추천.',ARRAY['일본속눈썹','라쉬리프트','가격']::text[],ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '55 hours'),
('Beautia','정보','전체',E'일본 드럭스토어 화장품 추천 2026 (쟁여올 템)',E'일본 가면 가성비 끝판왕 ✨\n\n· KATE 아이섀도우 — 데일리 무난\n· 세잔느(CEZANNE) 톤업 베이스·블러셔\n· 캔메이크 무치푸루 틴트(탕후루립 그거!)\n· 스킨아쿠아 톤업 UV (SPF50+/PA++++)\n\n💡 한 매장 5,000엔↑ 구매 시 여권 보여주면 면세!',ARRAY['일본화장품','드럭스토어','추천']::text[],ARRAY['https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '64 hours'),
('Beautia','정보','전체',E'일본 면세 받는 법 (드럭스토어·돈키 5,000엔)',E'일본 쇼핑 면세, 어렵지 않아요.\n\n· 한 매장에서 5,000엔 이상 → 여권 제시하면 면세\n· 드럭스토어·돈키호테는 외국인 쿠폰도 많음(앱·관광책자)\n· 면세품은 봉인 → 일본 내 개봉 주의\n\n화장품·뷰티템 쟁일 때 꼭 챙기세요.',ARRAY['일본면세','드럭스토어','쇼핑']::text[],ARRAY['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '73 hours'),
('Beautia','정보','전체',E'엔저 시대, 지금 일본 뷰티가 싼 이유',E'환율이 낮아 일본 미용·네일·속눈썹이 한국과 비슷하거나 더 쌀 때가 많아요.\n\n· 시술비는 현장 결제(일본은 팁 없음)\n· 여행/워홀 김에 머리·네일·속눈썹 한 번에 하는 분 많음\n\n어디가 좋은지·가격은 지역별로 beautia.io/info 에서 확인하세요.',ARRAY['엔저','일본뷰티','가성비']::text[],ARRAY['https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '82 hours'),
('Beautia','정보','전체',E'일본 다운펌 vs 매직 차이 (한국인 주의점)',E'헷갈리는 두 시술, 정리해드려요.\n\n· 다운펌(자연스럽게 볼륨 죽이기) → ストレートパーマ\n· 매직(강하게 쫙 펴기) → 縮毛矯正\n· 한국 다운펌 느낌을 원하면 ストレートパーマ로, 사진 보여주는 게 제일 정확\n\n출국 직전 강한 시술은 현지 손질이 어려워 비추예요.',ARRAY['다운펌','매직','일본미용실']::text[],ARRAY['https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '91 hours'),
('Beautia','정보','전체',E'일본 워홀 뷰티 알바 구하는 법 (미용실·네일)',E'일본 워홀로 뷰티 업계 일하고 싶다면?\n\n· 핫페퍼뷰티·Indeed·바이토루 등에 구인 많음\n· 신오쿠보·츠루하시 한인 미용실은 한국어 가능자 환영\n· 한국 미용 자격증 있으면 어시부터 시작 가능\n\nBeautia 커뮤니티 구인구직 게시판도 확인해보세요.',ARRAY['일본워홀','뷰티알바','구인구직']::text[],ARRAY['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '100 hours'),
('Beautia','정보','전체',E'일본 선크림·톤업 추천 (스킨아쿠아·아넷사)',E'여름 일본 갈 때 챙기면 좋은 자외선 차단:\n\n· 스킨아쿠아 톤업 UV (SPF50+/PA++++) — 메이크업 베이스 겸용\n· 비오레·아넷사(ANESSA) 자외선 차단 인기\n· 드럭스토어에서 면세로 저렴하게\n\n끈적임 적고 톤업까지 돼서 데일리로 좋아요.',ARRAY['일본선크림','톤업','드럭스토어']::text[],ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '109 hours');
