-- Beautia 정보글 일본어판 시드 (lang='ja') — 일본어 모드에서만 노출
-- lang 컬럼이 없으면 자동 추가 (이 파일만 실행해도 됨)
alter table public.posts add column if not exists lang text default 'ko';

insert into public.posts (nickname,cat,region,lang,title,content,tags,imgs,created_at) values
('Beautia','정보','전체','ja',E'ホットペッパービューティーで予約するコツ',E'サロン予約はホットペッパービューティーが定番です。\n\n・希望のスタイルは写真を保存して見せるのが一番伝わります\n・人気店・指名は埋まりやすいので早めの予約を\n・クーポンや初回メニューもチェック\n\nBeautiaは韓国のお客様の予約・通訳も代行しています。',ARRAY['予約','ホットペッパー','美容室']::text[],ARRAY['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '5 hours'),
('Beautia','정보','전체','ja',E'ジェルネイルの最新トレンド',E'日本のネイルはデザインの繊細さが魅力です。\n\n・マグネット・オーロラ・ミラー(ガラス)ネイルが人気\n・シンプルなワンカラーから派手めアートまで幅広い\n・やりたいデザインは写真を2〜3枚保存しておくとスムーズ\n\n地域・料金の目安は beautia.io/info で。',ARRAY['ネイル','ジェルネイル','トレンド']::text[],ARRAY['https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '13 hours'),
('Beautia','정보','전체','ja',E'デジタルパーマとコールドパーマの違い',E'パーマの種類を知っておくとオーダーが楽になります。\n\n・デジタルパーマ＝熱を使い、カールがはっきり&長持ち。乾かすとカールが出る\n・コールドパーマ(普通パーマ)＝薬剤のみ。濡れている時にカールが出やすい\n・C カール・S カールなど希望は写真で共有を\n\n髪質・長さで向き不向きがあるので相談を。',ARRAY['パーマ','デジタルパーマ','美容室']::text[],ARRAY['https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '21 hours'),
('Beautia','정보','전체','ja',E'カラー・ブリーチで失敗しないコツ',E'カラーやブリーチを受ける前のポイント。\n\n・なりたい色は「色の写真」で見せるのが正確\n・明るいブリーチは複数回かかることも。時間と予算に余裕を\n・根元染め＝リタッチカラー\n\nダメージや所要時間が気になる時は事前に確認を。',ARRAY['カラー','ブリーチ','リタッチ']::text[],ARRAY['https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '29 hours'),
('Beautia','정보','전체','ja',E'まつエクサロンの選び方',E'まつエク(まつ毛エクステ)を受ける時のチェックリスト。\n\n・衛生面：使い捨てツールを使っているか\n・デザイン：長さ(mm)・カール(C/D)・ボリュームを写真で\n・アレルギーが心配ならパッチテストの可否\n\n施術後は数時間洗顔を控えるので、予定の最後がおすすめ。',ARRAY['まつエク','アイラッシュ','サロン']::text[],ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '37 hours'),
('Beautia','정보','전체','ja',E'ドラッグストアで買える人気スキンケア',E'プチプラで優秀なスキンケアまとめ。\n\n・肌ラボ 極潤 化粧水 — 保湿のロングセラー\n・メラノCC — ビタミンC 美容液\n・キュレル — 敏感肌ライン\n\n海外の方は1店舗5,000円以上でパスポート提示すると免税対象です。',ARRAY['スキンケア','ドラッグストア','プチプラ']::text[],ARRAY['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '45 hours'),
('Beautia','정보','전체','ja',E'プチプラ リップ・ティント',E'ドラッグストアの人気リップ・ティント。\n\n・キャンメイク ムートンプルプル系ティント\n・KATE — デイリーに使いやすい\n・OPERA ティント オイルルージュ — うるツヤのロングセラー\n\nパーソナルカラー別の色番もまた紹介します。',ARRAY['リップ','ティント','コスメ']::text[],ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '53 hours'),
('Beautia','정보','전체','ja',E'美容室のマナー（指名料・遅刻・キャンセル）',E'美容室を利用する時のマナー。\n\n・チップ文化なし(表示価格＝支払額)\n・指名すると指名料がかかる場合あり\n・遅刻すると施術が短縮/中止になることも。時間厳守を\n・無断キャンセル・当日キャンセルはキャンセル料が発生する場合も\n\n予約変更は早めの連絡を。',ARRAY['美容室','マナー','予約']::text[],ARRAY['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '61 hours'),
('Beautia','정보','도쿄','ja',E'新宿で美容室・ネイル・まつエクをまとめて',E'新宿は都内最大の繁華街でサロンが密集しています。\n\n・新宿駅周辺はサロンが多く、遅くまで営業の店も\n・韓国系が多い新大久保もすぐ隣\n・髪+ネイルを1日でまとめて受けるのにも便利\n\n韓国語対応をご希望の方はBeautiaが通訳します。',ARRAY['新宿','東京','美容室','ネイル']::text[],ARRAY['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '69 hours'),
('Beautia','정보','도쿄','ja',E'渋谷の人気ヘアサロンの選び方',E'渋谷はトレンド感のあるヘアサロンが多いエリア。\n\n・指名制が一般的(指名料がつくことも)\n・なりたいスタイルは写真で見せるのが確実\n・人気店はウォークイン難しめ。事前予約を\n\n韓国式パーマ・ダウンパーマ希望はその旨を先に伝えると◎。',ARRAY['渋谷','東京','ヘア','美容室']::text[],ARRAY['https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '77 hours'),
('Beautia','정보','오사카','ja',E'心斎橋・難波でネイルを受ける',E'大阪のネイルは心斎橋・難波エリアに多いです。\n\n・ショッピング街の中心で観光の合間に寄りやすい\n・ジェル・アート・長さ出しまで対応、コスパの良い店も\n・デザインはInstagramの写真1枚でOK\n\n韓国語が不安でもBeautiaの通訳で予約できます。',ARRAY['心斎橋','難波','大阪','ネイル']::text[],ARRAY['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '85 hours'),
('Beautia','정보','전체','ja',E'韓国式ダウンパーマと縮毛矯正の違い',E'韓国で人気の「ダウンパーマ」が気になる方へ。\n\n・ダウンパーマ＝主に前髪/トップのボリュームを抑える部分的な施術\n・縮毛矯正＝髪全体をまっすぐにする\n・自然な毛流れを作りたいならダウンパーマが選ばれることが多い\n\nサロンにより呼び方・仕上がりが違うので写真で相談を。',ARRAY['ダウンパーマ','縮毛矯正','韓国ヘア']::text[],ARRAY['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '93 hours'),
('Beautia','정보','전체','ja',E'韓国人のお客様に人気の施術は？（サロン向け）',E'韓国からのお客様に人気の施術メモ(サロンさん向け)。\n\n・ヘア：ダウンパーマ、レイヤーカット、透明感カラー\n・ネイル：シンプル&マグネット、写真持参が多い\n・まつエク/眉:自然仕上げの相談が多い\n\nBeautiaは韓国のお客様の集客・予約・通訳を無料でサポートします。入店のお問い合わせはお気軽に。',ARRAY['サロン向け','韓国人集客','入店']::text[],ARRAY['https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '101 hours');
