-- Beautia 정보글 시드 2탄 (검증 내용 · 이미지는 주제에 맞는 것만)
insert into public.posts (nickname,cat,region,title,content,tags,imgs,created_at) values
('Beautia','정보','도쿄',E'신주쿠에서 미용실·네일·속눈썹 한 번에 받기',E'신주쿠(新宿)는 도쿄 최대 번화가라 미용실·네일·속눈썹샵이 다 모여 있어요.\n\n· 신주쿠역 주변 = 살롱 밀집, 늦게까지 영업하는 곳도 많음\n· 한인타운 신오쿠보(新大久保)가 바로 옆 → 한국어 가능 미용실도 가까움\n· 여행·워홀 일정에 머리+네일을 하루에 끝내기 좋아요\n\n예약·통역이 어려우면 Beautia가 한국어로 대행해드려요.',ARRAY['신주쿠','도쿄','미용실','네일']::text[],ARRAY['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '3 hours'),
('Beautia','정보','도쿄',E'시부야 헤어살롱 고르는 팁',E'시부야(渋谷)는 트렌디한 헤어살롱이 많은 동네예요.\n\n· 지명 디자이너 제도가 흔함(지명료가 붙기도)\n· 원하는 스타일은 사진으로 보여주는 게 가장 정확\n· 인기 살롱은 워크인 어려워 미리 예약 권장\n\n한국식 펌·다운펌을 원하면 그 점을 미리 전달하세요. (Beautia가 일본어로 통역)',ARRAY['시부야','도쿄','헤어','미용실']::text[],ARRAY['https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '10 hours'),
('Beautia','정보','오사카',E'신사이바시·난바에서 네일 받기',E'오사카 네일은 신사이바시(心斎橋)·난바(難波) 쪽에 많아요.\n\n· 쇼핑 거리 한가운데라 여행 동선에 끼우기 좋음\n· 젤·아트·연장 다 가능, 가성비 좋은 곳도 많음\n· 디자인은 핀터레스트/인스타 사진 1장이면 OK\n\n한국어 안 되는 곳도 Beautia 통역으로 예약 가능해요.',ARRAY['신사이바시','난바','오사카','네일']::text[],ARRAY['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '17 hours'),
('Beautia','정보','전체',E'일본 펌 종류 정리 — 디지털펌 vs 콜드펌',E'일본에서 펌 받기 전 종류만 알아둬도 소통이 쉬워요.\n\n· 디지털펌(デジタルパーマ) = 열을 줘서 컬이 또렷·오래감, 건조 후 컬 살아남\n· 콜드펌(コールドパーマ/普通パーマ) = 약으로만, 젖었을 때 컬이 더 살아남\n· C컬·S컬 등 원하는 컬 모양은 사진으로 전달\n\n모질·기장에 따라 추천이 달라지니 상담 내용도 통역해드려요.',ARRAY['일본펌','디지털펌','콜드펌','미용실']::text[],ARRAY['https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '24 hours'),
('Beautia','정보','전체',E'일본에서 염색·블리치, 한국과 다른 점',E'일본 염색·탈색 받기 전 참고하세요.\n\n· 원하는 톤은 \'색 사진\'으로 보여주는 게 정확(번호로만 말하면 달라질 수 있음)\n· 밝은 탈색은 여러 번 걸칠 수 있어 시간·비용 여유 두기\n· 뿌리염색 → リタッチカラー(리탓치카라)\n\n손상·시간 등 걱정되는 점은 미리 일본어로 확인해드려요.',ARRAY['일본염색','블리치','뿌리염색']::text[],ARRAY['https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '31 hours'),
('Beautia','정보','도쿄',E'도쿄 속눈썹샵 고를 때 체크리스트',E'도쿄에서 속눈썹(아이래시) 받을 때 확인하면 좋은 것.\n\n· 위생: 1회용 도구 사용 여부\n· 디자인: 길이(mm)·컬(C/D)·볼륨 정도를 사진으로\n· 알레르기 걱정되면 패치 테스트 가능한지\n· 속눈썹 전문샵 = まつエクサロン\n\n시술 후 몇 시간 세안 주의 → 일정 마지막에 받는 걸 추천.',ARRAY['도쿄','속눈썹','아이래시']::text[],ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '38 hours'),
('Beautia','정보','전체',E'일본 젤네일 디자인 트렌드',E'일본 네일은 디자인 디테일이 강점이에요.\n\n· 마그네틱(자석)·오로라·미러(글래스) 네일 인기\n· 심플 원컬러부터 화려한 아트까지 폭넓음\n· 원하는 디자인 사진 2~3장 저장해 가면 소통이 쉬움\n\n지역·가격은 beautia.io/info 에서 확인하세요.',ARRAY['일본네일','젤네일','디자인','트렌드']::text[],ARRAY['https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '45 hours'),
('Beautia','정보','전체',E'일본 드럭스토어 스킨케어 추천',E'일본 드럭스토어에서 사기 좋은 스킨케어예요.\n\n· 하다라보(肌ラボ) 고쿠쥰 토너 — 보습 스테디셀러\n· 멜라노CC — 비타민C 에센스/세럼\n· 큐레루(Curél) — 민감성 라인\n\n💡 한 매장 5,000엔↑ 구매 시 여권 보여주면 면세!',ARRAY['일본스킨케어','드럭스토어','추천']::text[],ARRAY['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '52 hours'),
('Beautia','정보','전체',E'일본 립·틴트 추천 (가성비)',E'일본 드럭스토어 립·틴트 인기템.\n\n· 캔메이크 무치푸루 틴트(탕후루립 그거!)\n· KATE 립 — 데일리 무난\n· OPERA 틴트 오일 루즈 — 촉촉 스테디셀러\n\n퍼스널컬러별로 호수 정리해서 또 올릴게요. 면세도 잊지 마세요.',ARRAY['일본립','틴트','드럭스토어','추천']::text[],ARRAY['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '59 hours'),
('Beautia','정보','전체',E'일본 미용실 매너 — 지명료·지각·노쇼',E'일본 미용실 이용 시 알아두면 좋은 매너.\n\n· 팁 문화 없음(표시가 = 결제가)\n· 디자이너 지명 시 지명료가 붙을 수 있음\n· 지각하면 시술이 축소/취소될 수 있어 시간 엄수\n· 노쇼·당일 취소는 캔슬료가 발생하기도\n\n예약 변경이 필요하면 미리 연락(또는 Beautia가 대신 연락)해드려요.',ARRAY['일본미용실','매너','예약']::text[],ARRAY['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '66 hours');
