-- Beautia 구인구직 시드 (검증된 가이드 + 실제 안내 · 사진 전부 다름 · 가짜 공고 없음)
-- Supabase SQL Editor에서 1회 실행 → 커뮤니티 '구인구직' 게시판 시드
insert into public.posts (nickname,cat,region,title,content,tags,imgs,created_at) values
('Beautia','구인구직','전체',E'[안내] 일본 한인 미용실·네일 구인 정보 — 사장님·구직자 환영',E'한·일 뷰티 구인을 Beautia 커뮤니티에서 연결해요.\n\n· 사람 구하는 사장님: 가게·시술분야·조건 적어서 글 올려주세요\n· 일자리 찾는 분: 경력·비자(워홀 등)·희망지역 적어주세요\n· 연락은 댓글 또는 Beautia 카톡 채널로\n\n허위 공고·개인정보 노출은 삼가주세요 🤍',ARRAY['구인구직','일본','워홀','안내']::text[],ARRAY['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '2 hours'),
('Beautia','구인구직','전체',E'일본 워홀 뷰티 알바 구하는 법 (핫페퍼·바이토루·한인 미용실)',E'일본 워홀로 미용·네일 알바 찾는 법 정리.\n\n· ホットペッパービューティー·Indeed·バイトル·タウンワーク 에 구인 많음\n· 신오쿠보(도쿄)·츠루하시(오사카) 한인 미용실은 한국어 가능자 환영\n· 사진 포트폴리오(인스타) 있으면 합격률 ↑\n· 워홀 비자로도 시급 알바 가능\n\n구체적 공고는 이 게시판·카톡으로 문의하세요.',ARRAY['일본워홀','뷰티알바','구인구직']::text[],ARRAY['https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '13 hours'),
('Beautia','구인구직','도쿄',E'[사장님] 한국 손님 받고 싶은 일본 살롱 — 구인 등록 무료',E'한국 손님을 받고 싶은 일본 미용실·네일·속눈썹 사장님께.\n\n· Beautia에 가게 프로필을 무료로 만들어드려요(사진·한국어OK 배지·공유 링크/QR)\n· 한국어 가능 스태프 구인 글도 올릴 수 있어요\n· 한국 손님 예약·통역은 Beautia가 대행\n\n관심 있으면 카톡 채널로 문의 주세요.',ARRAY['사장님','구인','입점','도쿄']::text[],ARRAY['https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '24 hours'),
('Beautia','구인구직','전체',E'일본 미용 알바 시급·조건 알아두기 (도쿄·오사카)',E'일본 미용 알바 기본 조건이에요.\n\n· 최저시급: 도쿄 약 ¥1,163 / 오사카 약 ¥1,114 (뷰티 스태프는 보통 그 이상 + 인센티브)\n· 교통비 지급·4대보험은 매장마다 다름\n· 지명·디자인 인센티브가 붙는 곳도 많음\n· 일본은 팁 문화 없음\n\n※ 시급·조건은 매장·시점에 따라 달라요.',ARRAY['일본알바','시급','구인구직']::text[],ARRAY['https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '35 hours'),
('Beautia','구인구직','전체',E'일본에서 미용 일하기 — 워홀·취로 비자 기본 정리',E'일본 미용 업계 취업 비자 기본만 짚어볼게요.\n\n· 워킹홀리데이: 1년(연장 가능), 시급 알바 자유로움\n· 취로 비자: 장기 근무 시, 고용주 스폰서 필요\n· 한국 미용 자격증이 있으면 어시스턴트부터 시작하는 경우 많음\n\n※ 비자는 상황별로 다르니 공식 정보로 꼭 재확인하세요.',ARRAY['일본취업','비자','워홀']::text[],ARRAY['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '46 hours'),
('Beautia','구인구직','전체',E'구직 팁: 포트폴리오·일본어로 어필하는 법',E'일본 뷰티 구직 시 합격률 높이는 팁.\n\n· 인스타 포트폴리오 링크 준비(작업 사진 위주)\n· 가능한 시술·경력 연수를 숫자로 명확히\n· 일본어 회화 수준 솔직하게(초/중/상)\n· 한국 손님 응대 가능 = 강점으로 어필\n\n구직 글 올릴 때 위 항목 넣으면 연락이 빨라요.',ARRAY['구직','포트폴리오','워홀']::text[],ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=720&q=70']::text[], now() - interval '57 hours');
